basePath: /api
definitions:
  actions.CategoryRequestAndResponse:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  actions.CreateOrUpdateCategoryRequest:
    properties:
      name:
        type: string
    type: object
  actions.GetUserResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  actions.UserLoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  actions.UserRegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  actions.UserTokenResponse:
    properties:
      token:
        type: string
    type: object
  services.Category:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  services.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost
info:
  contact: {}
  description: This is a Save My Pass API.
  title: Save My Pass - API
  version: "1.0"
paths:
  /category/all:
    get:
      consumes:
      - application/json
      description: Retrieves the categories for the logged-in user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/services.Category'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/services.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get list of categories
      tags:
      - Categories
  /category/create:
    post:
      consumes:
      - application/json
      description: Creates a new category with the provided name
      parameters:
      - description: Category name
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/actions.CreateOrUpdateCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.Category'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/services.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new category
      tags:
      - Categories
  /category/delete/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes the category with the given ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/actions.CategoryRequestAndResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/services.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete category
      tags:
      - Categories
  /category/update/{id}:
    put:
      consumes:
      - application/json
      description: Updates the category with the given ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category name
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/actions.CreateOrUpdateCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/actions.CategoryRequestAndResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/services.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update category
      tags:
      - Categories
  /user:
    get:
      consumes:
      - application/json
      description: Get information about the user
      produces:
      - application/json
      responses:
        "200":
          description: '{ ''id'': 6, ''name'': ''admin'', ''email'': ''admin@gmail.com''
            }'
          schema:
            $ref: '#/definitions/actions.GetUserResponse'
      security:
      - BearerAuth: []
      summary: Get user info
      tags:
      - Users
  /user/login:
    post:
      consumes:
      - application/json
      description: Log in a user using email and password
      parameters:
      - description: User Login
        in: body
        name: userLoginRequest
        required: true
        schema:
          $ref: '#/definitions/actions.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{"token": "jakjdslskldaew"}'
          schema:
            $ref: '#/definitions/actions.UserTokenResponse'
        "400":
          description: '{"error": "error"}'
          schema:
            $ref: '#/definitions/services.ErrorResponse'
        "500":
          description: '{"error": "error"}'
          schema:
            $ref: '#/definitions/services.ErrorResponse'
      summary: User login
      tags:
      - Users
  /user/register:
    post:
      consumes:
      - application/json
      description: Register user by Email, Name and Password
      parameters:
      - description: User Registration
        in: body
        name: userRegisterRequest
        required: true
        schema:
          $ref: '#/definitions/actions.UserRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{"token": "jakjdslskldaew"}'
          schema:
            $ref: '#/definitions/actions.UserTokenResponse'
        "400":
          description: '{"error": "error"}'
          schema:
            $ref: '#/definitions/services.ErrorResponse'
        "500":
          description: '{"error": "error"}'
          schema:
            $ref: '#/definitions/services.ErrorResponse'
      summary: Register user
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
